site_name: Il sito di Alessandra
site_url: https://mydomain.org/mysite
theme:
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - content.code.copy
  language: it
  logo: assets/playstation.png
  name: material
  font: 
    text: Roboto Mono
  palette:
    - scheme: default
      primary: purple
      accent: pink
      toggle:
        icon: material/eye
        name: Switch to dark mode

    - scheme: slate
      primary: black
      accent: pink
      toggle:
        icon: material/eye-outline
        name: Switch to light mode

nav:
  - Bio: index.md
  - Annotazioni: about.md
  - Groviglio Entropico: Groviglio.md

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

extra:
  consent:
    cookies:
      analytics: ti prego, lascia stare la mia famiglia 
    description: >- 
      Gentile Utente, la informiamo che accettando i Termini e le Condizioni di servizio
      saremo in grado di intercettare i suoi dati, di identificare i suoi tratti di ricerca
      quotidiani e, occasionalmente, verificare mediante i suoi dispositivi muniti di videocamera
      e/o strumenti di videosorveglianza se ha consumato almeno tre pasti completi al giorno.

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption



markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences